kind: pipeline
type: docker
name: add-server-ci

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - main
  event:
    include:
    - push
    - pull_request

steps:
- name: test
  pull: if-not-exists
  image: golang:1.15.2
  commands:
  - cd src
  - go mod download
  - go test -v ./...
- name: build-image
  <<: *x-build-docker-image
  settings:
    repo: minghsu0107/cicd-demo
    dockerfile: src/Dockerfile
    context: src
  depends_on:
    - test
- name: update-manifests
  pull: if-not-exists
  image: line/kubectl-kustomize:1.20.2-3.9.1
  environment:
    SSH_KEY:
      from_secret: ssh_key
  commands:
  - apk update && apk add --no-cache git && apk add --no-cache openssh
  - mkdir -p ~/.ssh && echo $SSH_KEY | base64 -d > ~/.ssh/id_rsa && chmod 700 ~/.ssh/id_rsa && ssh-keyscan github.com >> ~/.ssh/known_hosts
  - rm -rf cicd-demo-manifests && git clone ssh://git@github.com/minghsu0107/cicd-demo-manifests.git
  - cd cicd-demo-manifests/production && kustomize edit set image minghsu0107/cicd-demo:$DRONE_COMMIT_SHA
  - git add . && git commit -m "update to $DRONE_COMMIT_SHA"
  - git push ssh://git@github.com/minghsu0107/cicd-demo-manifests.git
  depends_on:
    - build-image
