kind: pipeline
type: docker
name: add-server-ci

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - main
  event:
    include:
    - push
    - pull_request

steps:
- name: test
  pull: if-not-exists
  image: golang:1.15.2
  commands:
  - cd src
  - go mod download
  - go test -v ./...
- name: build-image
  <<: *x-build-docker-image
  settings:
    repo: minghsu0107/cicd-demo
    dockerfile: src/Dockerfile
    context: src
  depends_on:
    - test
- name: update-manifests
  pull: if-not-exists
  image: minghsu0107/update-kustomization:v1.1.2
  environment:
    SSH_KEY:
      from_secret: ssh_key
    IMAGES: minghsu0107/cicd-demo
    IMAGE_TAG: ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    MANIFEST_HOST: github.com
    MANIFEST_USER: minghsu0107
    MANIFEST_USER_EMAIL: minghsu0107@gmail.com
    MANIFEST_REPO: cicd-demo-manifests
    MANIFEST_BRANCH: main
    KUSTOMIZATION: production
  depends_on:
    - build-image
  when:
    event: push
